FROM node:18 AS build-stage

WORKDIR /app/src

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:18

WORKDIR /app/src

COPY --from=build-stage /app/package*.json ./
COPY --from=build-stage /app/dist ./dist

RUN npm install --only=production

EXPOSE 8080
CMD ["node", "dist/index.js"]

